create table Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) not null,
    age int CHECK ( age > 0 ) not null
);


create table Book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int references Person(id),
    title varchar(200) not null,
    author varchar(100) not null,
    year int CHECK ( year > 1900 ) not null,
    taken_at timestamp
);


